name: USB Virus Scanner

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile usb_virus_scanner.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: usb-virus-scanner
        path: dist/usb_virus_scanner.exe
